version: "3"

services:
  postgres:
    container_name: postgres
    image: 'postgres:14-alpine'
    environment: 
      POSTGRES_DB: '${POSTGRES_DB:-calendar}'
      POSTGRES_USER: '${POSTGRES_USER:-calendar_user}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-secret}'
      PGDATA: '/var/lib/postgresql/data'
    ports: 
      - '${DATABASE_PORT:-5432}:5432'
    volumes:
        - calendar_postgres:/var/lib/postgresql/data
  
  zookeeper:
    container_name: zookeeper
    image: 'bitnami/zookeeper:latest'
    ports:
      - '${ZOOKEEPER_PORT:-2181}:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    container_name: kafka
    image: 'bitnami/kafka:3.2'
    ports:
      - '${KAFKA_PORT:-9093}:9093'
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_CFG_ZOOKEEPER_CONNECT: zookeeper:${ZOOKEEPER_PORT:-2181}
      ALLOW_PLAINTEXT_LISTENER: 'yes'
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: CLIENT:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_CFG_LISTENERS: CLIENT://:9092,EXTERNAL://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: CLIENT://kafka:9092,EXTERNAL://localhost:9093
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: CLIENT
    depends_on:
      - zookeeper
    restart: always

  kafka-ui:
    container_name: kafka_ui
    image: 'provectuslabs/kafka-ui:latest'
    ports:
      - '${KAFKA_UI_PORT:-22181}:8080'
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
    depends_on:
      - kafka

volumes:
  calendar_postgres:
    name: 'calendar-postgres'