[logger]
level = "INFO"

[storage]
driver = "sql" # memory, sql

[database] # используется только при driver=sql
dsn = "postgres://calendar_user:secret@localhost:55432/calendar"

[http]
addr = ":8080"
requestLogFile = "/logs/http-server.log"

[grpc]
addr = ":9000"
requestLogFile = "./logs/grpc-server.log"