[logger]
level = "DEBUG"

[database]
dsn = "postgres://calendar_user:secret@localhost:55432/calendar"

[broker]
adapter = "kafka"
address = "localhost:9093"

[dbWorker]
scanPeriod = "1m"
clearPeriodDays = 365
