[logger]
level = "DEBUG"

[database]
dsn = "postgres://calendar_user:secret@postgres:5432/calendar"
maxConnectionTries = 5
connectionTryDelay = "3s"

[broker]
adapter = "kafka"
address = "kafka:9093"
topic = "notifications"
version = "3.2.0"
maxConnectionTries = 5
connectionTryDelay = "3s"

[dbWorker]
scanPeriod = "1m"
clearPeriodDays = 365
