[logger]
level = "DEBUG"

[broker]
adapter = "kafka"
# https://github.com/Shopify/sarama/issues/1683
address = "10.5.0.7:9092"
topic = "notifications"
version = "3.2.0"
maxConnectionTries = 5
connectionTryDelay = "3s"

[file]
path =  "./logs/email.log"